---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redev
  labels:
    app: redev
    type: demo
    poc: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redev
      type: demo
      poc: redis
  template:
    metadata:
      labels:
        app: redev
        type: demo
        poc: redis
    spec:
      initContainers:
      - name: init
        image: goodsmileduck/redis-cli
        env:
        - name: REDEV_ENDPOINT
          value: "redisdev-master.cache.svc.cluster.local"
        command:
        - sh
        - -c
        - redis-cli
        - -h $REDEV_ENDPOINT
        - -p 6379 
        - ping
      containers:
      - name: redev
        image: "dukecyber/demo-redev:0.1.0"
        imagePullPolicy: "Always"
        env:
        - name: REDEV_ENDPOINT
          value: "redev-cluster.cache.svc.cluster.local:6379"
        - name: REDEV_PASSWORD
          value: "P@ssw0rd"
        - name: REDEV_INIT_DB
          value: "0"
        - name: REDEV_ROUND
          value: "300"